export const columnNames = [
  {
    id: 'id',
    name: 'OneSignal Player Id',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'identifier',
    name: 'Push Token',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'session_count',
    name: 'Number of times they visited the app or site',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'language',
    name: 'Device language code',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'timezone',
    name: 'Number of seconds away from UTC. Example: -28800',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'game_version',
    name: 'Version of your mobile app gathered from Android Studio `versionCode` in your App/build.gradle and iOS uses `kCFBundleVersionKey` in Xcode.',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'device_os',
    name: 'Device Operating System Version. Example: 80 = Chrome 80, 9 = Android 9',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'device_type',
    name: 'Device Operating System Type. Device Operating System Type. Example:0 = iOS mobile app, 1 = Android mobile app, 5 = Chrome Web Push',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'device_model',
    name: "Device Hardware String Code.Example: Mobile Web Subscribers will have 'Linux armv'",
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'ad_id',
    name: 'Based on the Google Advertising Id for Android, identifierForVendor for iOS. Means user turned off Advertising tracking on the device.',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'tags',
    name: 'Current OneSignal Data Tags on the device.',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'last_active',
    name: 'Date and time the user last opened the mobile app or visited the site based on UTC.',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'playtime',
    name: 'Total amount of time in seconds the user had the mobile app open.',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'amount_spent',
    name: 'Mobile only - amount spent in USD on In-App Purchases.',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'created_at',
    name: 'Date and time the device record was created in OneSignal.',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'invalid_identifier',
    name: 't = unsubscribed, f = subscibed',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'badge_count',
    name: 'Current number of badges on the device',
    disabled: true,
    canBeDisabled: !true,
    value: true,
  },
  {
    id: 'external_user_id',
    name: 'Your User Id set on the device.',
    disabled: false,
    canBeDisabled: !false,
    value: false,
  },
  {
    id: 'notification_types',
    name: 'Notification Types',
    disabled: false,
    canBeDisabled: !false,
    value: false,
  },
  {
    id: 'location',
    name: 'Location points (Latitude and Longitude) set on the device.',
    disabled: false,
    canBeDisabled: !false,
    value: false,
  },
  {
    id: 'country',
    name: 'Country code',
    disabled: false,
    canBeDisabled: !false,
    value: false,
  },
  {
    id: 'rooted',
    name: 'Android device rooted or not',
    disabled: false,
    canBeDisabled: !false,
    value: false,
  },
  {
    id: 'ip',
    name: 'IP Address of the device if being tracked.',
    disabled: false,
    canBeDisabled: !false,
    value: false,
  },
  {
    id: 'web_auth',
    name: 'Web Only authorization key.',
    disabled: true,
    canBeDisabled: true,
    value: true,
  },
  {
    id: 'web_p256',
    name: 'Web Only p256 key.',
    disabled: true,
    canBeDisabled: true,
    value: true,
  },
];
